APP_NAME=TenantBackend
APP_ENV=production
APP_KEY={{APP_KEY}}
APP_DEBUG=false
APP_URL={{APP_URL}}
TENANT_PORTAL_URL={{TENANT_PORTAL_URL}}

APP_LOCALE=de
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

LOG_CHANNEL=stack
LOG_STACK=single
LOG_LEVEL=info

DB_CONNECTION=mysql
DB_HOST={{DB_HOST}}
DB_PORT={{DB_PORT}}
DB_DATABASE={{DB_DATABASE}}
DB_USERNAME={{DB_USERNAME}}
DB_PASSWORD={{DB_PASSWORD}}

CACHE_STORE=file
QUEUE_CONNECTION=database
SESSION_DRIVER=file
FILESYSTEM_DISK=local

MAIL_MAILER={{MAIL_MAILER}}
MAIL_HOST={{MAIL_HOST}}
MAIL_PORT={{MAIL_PORT}}
MAIL_USERNAME={{MAIL_USERNAME}}
MAIL_PASSWORD={{MAIL_PASSWORD}}
MAIL_ENCRYPTION={{MAIL_ENCRYPTION}}
MAIL_FROM_ADDRESS={{MAIL_FROM_ADDRESS}}
MAIL_FROM_NAME="Tenant Portal"

LICENSE_API_URL={{LICENSE_API_URL}}
CORE_API_TOKEN={{CORE_API_TOKEN}}
CORE_TO_TENANT_SYNC_TOKEN={{CORE_TO_TENANT_SYNC_TOKEN}}
AUTO_LICENSE_SYNC_ENABLED={{AUTO_LICENSE_SYNC_ENABLED}}
E2E_CORE_TENANT_UUID={{E2E_CORE_TENANT_UUID}}
MFA_APP_ACTIVATION_TTL_MINUTES=30
LOGIN_RATE_LIMIT=5
MFA_VERIFY_RATE_LIMIT=5
MFA_CODE_TTL_MINUTES=10
TRUSTED_DEVICE_TTL_DAYS=30
TRUSTED_DEVICE_COOKIE=tenant_trusted_device
PASSWORD_MIN_LENGTH=12
JWT_ACTIVE_KID=default
JWT_KEYS_JSON=
JWT_TTL_MINUTES=480
JWT_REFRESH_TTL_MINUTES=10080
JWT_SECRET={{JWT_SECRET}}
NOTIFICATIONS_STREAM_ENABLED=false
